### ISSUE TITLE
Python2/3 mishandling bug

### ISSUE THREAD

**Issue by An7ar35** [cjlee112/pygr#4]
Compatibility issue with Arch/Python3 (Arch linux installs defaults python3 on /usr/bin/python) so when runing ````pip install pygr```` the result is:

~~~~
Collecting pygr
  Using cached pygr-0.8.2.tar.gz
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-build-tge2rfff/pygr/setup.py", line 19
        print 'Setuptools not imported, falling back to distutils'
                                                                 ^
    SyntaxError: Missing parentheses in call to 'print'
   
    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-build-tge2rfff/pygr/
Collecting pyhgvs
  Could not find a version that satisfies the requirement pyhgvs (from versions: )
No matching distribution found for pyhgvs
~~~~

**Comment by martyheil** [comment]
I'm also experiencing this issue. It seems the setup.py file contains python2 syntax so when attempting to install for python3 there are issues with the syntax. Going through the setup.py file and updating the syntax should do the trick. That is if this package is being supported in python3 otherwise python2 will be necessary.
